# Generated by Django 2.2.13 on 2021-08-02 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0009_auto_20210802_1718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='anonymous',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='topic',
            name='anonymous',
            field=models.BooleanField(),
        ),
    ]
